
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Exceptions de Django &#8212; Documentation Django 3.1.3.dev</title>
    <link rel="stylesheet" href="../_static/default.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <script type="text/javascript" src="../_static/language_data.js"></script>
    <script type="text/javascript" src="../_static/translations.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Recherche" href="../search.html" />
    <link rel="next" title="Gestion des fichiers" href="files/index.html" />
    <link rel="prev" title="django-admin et manage.py" href="django-admin.html" />



 
<script src="../templatebuiltins.js"></script>
<script>
(function($) {
    if (!django_template_builtins) {
       // templatebuiltins.js missing, do nothing.
       return;
    }
    $(document).ready(function() {
        // Hyperlink Django template tags and filters
        var base = "templates/builtins.html";
        if (base == "#") {
            // Special case for builtins.html itself
            base = "";
        }
        // Tags are keywords, class '.k'
        $("div.highlight\\-html\\+django span.k").each(function(i, elem) {
             var tagname = $(elem).text();
             if ($.inArray(tagname, django_template_builtins.ttags) != -1) {
                 var fragment = tagname.replace(/_/, '-');
                 $(elem).html("<a href='" + base + "#" + fragment + "'>" + tagname + "</a>");
             }
        });
        // Filters are functions, class '.nf'
        $("div.highlight\\-html\\+django span.nf").each(function(i, elem) {
             var filtername = $(elem).text();
             if ($.inArray(filtername, django_template_builtins.tfilters) != -1) {
                 var fragment = filtername.replace(/_/, '-');
                 $(elem).html("<a href='" + base + "#" + fragment + "'>" + filtername + "</a>");
             }
        });
    });
})(jQuery);</script>

  </head><body>

    <div class="document">
  <div id="custom-doc" class="yui-t6">
    <div id="hd">
      <h1><a href="../index.html">Documentation Django 3.1.3.dev</a></h1>
      <div id="global-nav">
        <a title="Home page" href="../index.html">Home</a>  |
        <a title="Table of contents" href="../contents.html">Table of contents</a>  |
        <a title="Global index" href="../genindex.html">Index</a>  |
        <a title="Module index" href="../py-modindex.html">Modules</a>
      </div>
      <div class="nav">
    &laquo; <a href="django-admin.html" title="&lt;code class=&#34;docutils literal notranslate&#34;&gt;&lt;span class=&#34;pre&#34;&gt;django-admin&lt;/span&gt;&lt;/code&gt; et &lt;code class=&#34;docutils literal notranslate&#34;&gt;&lt;span class=&#34;pre&#34;&gt;manage.py&lt;/span&gt;&lt;/code&gt;">previous</a>
     |
    <a href="index.html" title="Référence de l’API" accesskey="U">up</a>
   |
    <a href="files/index.html" title="Gestion des fichiers">next</a> &raquo;</div>
    </div>

    <div id="bd">
      <div id="yui-main">
        <div class="yui-b">
          <div class="yui-g" id="ref-exceptions">
            
  <div class="section" id="s-django-exceptions">
<span id="django-exceptions"></span><h1>Exceptions de Django<a class="headerlink" href="#django-exceptions" title="Lien permanent vers ce titre">¶</a></h1>
<p>Django peut aussi bien générer des exceptions qu’il définit lui-même que des exceptions Python standards.</p>
<div class="section" id="s-module-django.core.exceptions">
<span id="s-django-core-exceptions"></span><span id="module-django.core.exceptions"></span><span id="django-core-exceptions"></span><h2>Exceptions principales de Django<a class="headerlink" href="#module-django.core.exceptions" title="Lien permanent vers ce titre">¶</a></h2>
<p>Les classes d’exception de base de Django sont définies dans <code class="docutils literal notranslate"><span class="pre">django.core.exceptions</span></code>.</p>
<div class="section" id="s-appregistrynotready">
<span id="appregistrynotready"></span><h3><code class="docutils literal notranslate"><span class="pre">AppRegistryNotReady</span></code><a class="headerlink" href="#appregistrynotready" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.AppRegistryNotReady">
<em class="property">exception </em><code class="descname">AppRegistryNotReady</code><a class="reference internal" href="../_modules/django/core/exceptions.html#AppRegistryNotReady"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.AppRegistryNotReady" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>Cette exception est générée lorsqu’on essaie d’utiliser des modèles avant que le <a class="reference internal" href="applications.html#app-loading-process"><span class="std std-ref">processus de chargement des applications</span></a>, qui initialise l’ORM, soit terminé.</p>
</dd></dl>

</div>
<div class="section" id="s-objectdoesnotexist">
<span id="objectdoesnotexist"></span><h3><code class="docutils literal notranslate"><span class="pre">ObjectDoesNotExist</span></code><a class="headerlink" href="#objectdoesnotexist" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ObjectDoesNotExist">
<em class="property">exception </em><code class="descname">ObjectDoesNotExist</code><a class="reference internal" href="../_modules/django/core/exceptions.html#ObjectDoesNotExist"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.ObjectDoesNotExist" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>La classe de base des exceptions <a class="reference internal" href="models/class.html#django.db.models.Model.DoesNotExist" title="django.db.models.Model.DoesNotExist"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Model.DoesNotExist</span></code></a>. Une clause <code class="docutils literal notranslate"><span class="pre">try/except</span></code> avec <code class="docutils literal notranslate"><span class="pre">ObjectDoesNotExist</span></code> intercepte les exceptions <a class="reference internal" href="models/class.html#django.db.models.Model.DoesNotExist" title="django.db.models.Model.DoesNotExist"><code class="xref py py-exc docutils literal notranslate"><span class="pre">DoesNotExist</span></code></a> de tous les modèles.</p>
<p>Voir <a class="reference internal" href="models/querysets.html#django.db.models.query.QuerySet.get" title="django.db.models.query.QuerySet.get"><code class="xref py py-meth docutils literal notranslate"><span class="pre">get()</span></code></a>.</p>
</dd></dl>

</div>
<div class="section" id="s-emptyresultset">
<span id="emptyresultset"></span><h3><code class="docutils literal notranslate"><span class="pre">EmptyResultSet</span></code><a class="headerlink" href="#emptyresultset" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.EmptyResultSet">
<em class="property">exception </em><code class="descname">EmptyResultSet</code><a class="reference internal" href="../_modules/django/core/exceptions.html#EmptyResultSet"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.EmptyResultSet" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p><code class="docutils literal notranslate"><span class="pre">EmptyResultSet</span></code> peut être généré durant la construction de la requête si celle-ci ne renvoie aucun résultat. La plupart des projets Django ne rencontreront pas cette exception, mais elle peut être utile pour implémenter des interrogations ou des expressions personnalisées.</p>
</dd></dl>

</div>
<div class="section" id="s-fielddoesnotexist">
<span id="fielddoesnotexist"></span><h3><code class="docutils literal notranslate"><span class="pre">FieldDoesNotExist</span></code><a class="headerlink" href="#fielddoesnotexist" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.FieldDoesNotExist">
<em class="property">exception </em><code class="descname">FieldDoesNotExist</code><a class="reference internal" href="../_modules/django/core/exceptions.html#FieldDoesNotExist"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.FieldDoesNotExist" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <code class="docutils literal notranslate"><span class="pre">FieldDoesNotExist</span></code> est produite par une méthode <code class="docutils literal notranslate"><span class="pre">_meta.get_field()</span></code> d’un modèle lorsque le champ demandé n’existe pas dans le modèle, ni dans les parents du modèle.</p>
</dd></dl>

</div>
<div class="section" id="s-multipleobjectsreturned">
<span id="multipleobjectsreturned"></span><h3><code class="docutils literal notranslate"><span class="pre">MultipleObjectsReturned</span></code><a class="headerlink" href="#multipleobjectsreturned" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.MultipleObjectsReturned">
<em class="property">exception </em><code class="descname">MultipleObjectsReturned</code><a class="reference internal" href="../_modules/django/core/exceptions.html#MultipleObjectsReturned"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.MultipleObjectsReturned" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>La classe de base des exceptions <a class="reference internal" href="models/class.html#django.db.models.Model.MultipleObjectsReturned" title="django.db.models.Model.MultipleObjectsReturned"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Model.MultipleObjectsReturned</span></code></a>. Une clause <code class="docutils literal notranslate"><span class="pre">try/except</span></code> avec <code class="docutils literal notranslate"><span class="pre">MultipleObjectsReturned</span></code> intercepte les exceptions <a class="reference internal" href="models/class.html#django.db.models.Model.MultipleObjectsReturned" title="django.db.models.Model.MultipleObjectsReturned"><code class="xref py py-exc docutils literal notranslate"><span class="pre">MultipleObjectsReturned</span></code></a> de tous les modèles.</p>
<p>Voir <a class="reference internal" href="models/querysets.html#django.db.models.query.QuerySet.get" title="django.db.models.query.QuerySet.get"><code class="xref py py-meth docutils literal notranslate"><span class="pre">get()</span></code></a>.</p>
</dd></dl>

</div>
<div class="section" id="s-suspiciousoperation">
<span id="suspiciousoperation"></span><h3><code class="docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code><a class="headerlink" href="#suspiciousoperation" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.SuspiciousOperation">
<em class="property">exception </em><code class="descname">SuspiciousOperation</code><a class="reference internal" href="../_modules/django/core/exceptions.html#SuspiciousOperation"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.SuspiciousOperation" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.core.exceptions.SuspiciousOperation" title="django.core.exceptions.SuspiciousOperation"><code class="xref py py-exc docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code></a> est générée lorsqu’un utilisateur effectue une opération considérée comme douteuse selon des critères de sécurité, comme lors de manipulations d’un cookie de session. Les sous-classes de <code class="docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code> comprennent&nbsp;:</p>
<ul class="simple">
<li><code class="docutils literal notranslate"><span class="pre">DisallowedHost</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">DisallowedModelAdminLookup</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">DisallowedModelAdminToField</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">DisallowedRedirect</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">InvalidSessionKey</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">RequestDataTooBig</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">SuspiciousFileOperation</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">SuspiciousMultipartForm</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">SuspiciousSession</span></code></li>
<li><code class="docutils literal notranslate"><span class="pre">TooManyFieldsSent</span></code></li>
</ul>
<p>Si une exception <code class="docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code> atteint le niveau du gestionnaire ASGI/WSGI, elle est journalisée au niveau <code class="docutils literal notranslate"><span class="pre">Error</span></code> et produit une exception <a class="reference internal" href="request-response.html#django.http.HttpResponseBadRequest" title="django.http.HttpResponseBadRequest"><code class="xref py py-class docutils literal notranslate"><span class="pre">HttpResponseBadRequest</span></code></a>. Consultez la <a class="reference internal" href="../topics/logging.html"><span class="doc">documentation de la journalisation</span></a> pour plus d’informations.</p>
</dd></dl>

</div>
<div class="section" id="s-permissiondenied">
<span id="permissiondenied"></span><h3><code class="docutils literal notranslate"><span class="pre">PermissionDenied</span></code><a class="headerlink" href="#permissiondenied" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.PermissionDenied">
<em class="property">exception </em><code class="descname">PermissionDenied</code><a class="reference internal" href="../_modules/django/core/exceptions.html#PermissionDenied"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.PermissionDenied" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.core.exceptions.PermissionDenied" title="django.core.exceptions.PermissionDenied"><code class="xref py py-exc docutils literal notranslate"><span class="pre">PermissionDenied</span></code></a> est générée lorsqu’un utilisateur ne possède pas la permission d’effectuer l’action demandée.</p>
</dd></dl>

</div>
<div class="section" id="s-viewdoesnotexist">
<span id="viewdoesnotexist"></span><h3><code class="docutils literal notranslate"><span class="pre">ViewDoesNotExist</span></code><a class="headerlink" href="#viewdoesnotexist" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ViewDoesNotExist">
<em class="property">exception </em><code class="descname">ViewDoesNotExist</code><a class="reference internal" href="../_modules/django/core/exceptions.html#ViewDoesNotExist"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.ViewDoesNotExist" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.core.exceptions.ViewDoesNotExist" title="django.core.exceptions.ViewDoesNotExist"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ViewDoesNotExist</span></code></a> est générée par <a class="reference internal" href="urlresolvers.html#module-django.urls" title="django.urls"><code class="xref py py-mod docutils literal notranslate"><span class="pre">django.urls</span></code></a> lorsqu’une vue demandée n’existe pas.</p>
</dd></dl>

</div>
<div class="section" id="s-middlewarenotused">
<span id="middlewarenotused"></span><h3><code class="docutils literal notranslate"><span class="pre">MiddlewareNotUsed</span></code><a class="headerlink" href="#middlewarenotused" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.MiddlewareNotUsed">
<em class="property">exception </em><code class="descname">MiddlewareNotUsed</code><a class="reference internal" href="../_modules/django/core/exceptions.html#MiddlewareNotUsed"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.MiddlewareNotUsed" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.core.exceptions.MiddlewareNotUsed" title="django.core.exceptions.MiddlewareNotUsed"><code class="xref py py-exc docutils literal notranslate"><span class="pre">MiddlewareNotUsed</span></code></a> est générée lorsqu’un middleware n’est pas utilisé dans la configuration du serveur.</p>
</dd></dl>

</div>
<div class="section" id="s-improperlyconfigured">
<span id="improperlyconfigured"></span><h3><code class="docutils literal notranslate"><span class="pre">ImproperlyConfigured</span></code><a class="headerlink" href="#improperlyconfigured" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ImproperlyConfigured">
<em class="property">exception </em><code class="descname">ImproperlyConfigured</code><a class="reference internal" href="../_modules/django/core/exceptions.html#ImproperlyConfigured"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.ImproperlyConfigured" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.core.exceptions.ImproperlyConfigured" title="django.core.exceptions.ImproperlyConfigured"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ImproperlyConfigured</span></code></a> est générée lorsque la configuration de Django contient une erreur, par exemple si une valeur de <code class="docutils literal notranslate"><span class="pre">settings.py</span></code> n’est pas correcte ou ne peut pas être lue correctement.</p>
</dd></dl>

</div>
<div class="section" id="s-fielderror">
<span id="fielderror"></span><h3><code class="docutils literal notranslate"><span class="pre">FieldError</span></code><a class="headerlink" href="#fielderror" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.FieldError">
<em class="property">exception </em><code class="descname">FieldError</code><a class="reference internal" href="../_modules/django/core/exceptions.html#FieldError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.FieldError" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.core.exceptions.FieldError" title="django.core.exceptions.FieldError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">FieldError</span></code></a> est générée lorsqu’il y a un problème avec un champ de modèle. Ceci peut arriver pour plusieurs raisons&nbsp;:</p>
<ul class="simple">
<li>Un champ de modèle est en conflit avec un champ de même nom provenant d’une classe de base abstraite.</li>
<li>Un ordre de tri provoque une boucle sans fin.</li>
<li>Un mot-clé ne peut pas être lu dans les paramètres d’un filtre.</li>
<li>Il n’est pas possible de faire correspondre un paramètre nommé d’une requête avec un champ.</li>
<li>Une jointure n’est pas autorisée sur le champ indiqué.</li>
<li>Un nom de champ n’est pas valide.</li>
<li>Une requête contient des paramètres <code class="docutils literal notranslate"><span class="pre">order_by</span></code> non conformes.</li>
</ul>
</dd></dl>

</div>
<div class="section" id="s-validationerror">
<span id="validationerror"></span><h3><code class="docutils literal notranslate"><span class="pre">ValidationError</span></code><a class="headerlink" href="#validationerror" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ValidationError">
<em class="property">exception </em><code class="descname">ValidationError</code><a class="reference internal" href="../_modules/django/core/exceptions.html#ValidationError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.ValidationError" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.core.exceptions.ValidationError" title="django.core.exceptions.ValidationError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ValidationError</span></code></a> est générée lorsque des données font échouer la validation de formulaire ou de champ de modèle. Pour plus d’informations sur la validation, consultez <a class="reference internal" href="forms/validation.html"><span class="doc">Validation des formulaires et des champs</span></a>, <a class="reference internal" href="models/instances.html#validating-objects"><span class="std std-ref">Validation des champs de modèle</span></a> et <a class="reference internal" href="validators.html"><span class="doc">Référence de la validation</span></a>.</p>
</dd></dl>

<div class="section" id="s-non-field-errors">
<span id="non-field-errors"></span><h4><code class="docutils literal notranslate"><span class="pre">NON_FIELD_ERRORS</span></code><a class="headerlink" href="#non-field-errors" title="Lien permanent vers ce titre">¶</a></h4>
<dl class="data">
<dt id="django.core.exceptions.NON_FIELD_ERRORS">
<code class="descname">NON_FIELD_ERRORS</code><a class="headerlink" href="#django.core.exceptions.NON_FIELD_ERRORS" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<p>Les exceptions <code class="docutils literal notranslate"><span class="pre">ValidationError</span></code> qui ne sont pas liées à un champ particulier d’un formulaire ou d’un modèle sont classées comme <code class="docutils literal notranslate"><span class="pre">NON_FIELD_ERRORS</span></code>. Cette constante est utilisée comme clé dans des dictionnaires qui habituellement font correspondre des champs à leur liste d’erreurs respective.</p>
</div>
</div>
<div class="section" id="s-requestaborted">
<span id="requestaborted"></span><h3><code class="docutils literal notranslate"><span class="pre">RequestAborted</span></code><a class="headerlink" href="#requestaborted" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.RequestAborted">
<em class="property">exception </em><code class="descname">RequestAborted</code><a class="reference internal" href="../_modules/django/core/exceptions.html#RequestAborted"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.RequestAborted" title="Lien permanent vers cette définition">¶</a></dt>
<dd><div class="versionadded">
<span class="title">New in Django 3.0.</span> </div>
<p>L’exception <a class="reference internal" href="#django.core.exceptions.RequestAborted" title="django.core.exceptions.RequestAborted"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RequestAborted</span></code></a> est produite lorsqu’un corps de requête HTTP en cours de lecture par le gestionnaire est interrompu prématurément et que la connexion cliente est fermée, ou quand le client n’envoie pas de données et dépasse le délai après lequel le serveur coupe la connexion.</p>
<p>Elle est interne aux modules de gestion HTTP et il est rare de la voir ailleurs. SI vous modifiez du code de gestion HTTP, vous devriez générer cette exception lorsque vous êtes confronté à une requête interrompue pour être sûr que le connecteur soit proprement fermé.</p>
</dd></dl>

</div>
<div class="section" id="s-synchronousonlyoperation">
<span id="synchronousonlyoperation"></span><h3><code class="docutils literal notranslate"><span class="pre">SynchronousOnlyOperation</span></code><a class="headerlink" href="#synchronousonlyoperation" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.SynchronousOnlyOperation">
<em class="property">exception </em><code class="descname">SynchronousOnlyOperation</code><a class="reference internal" href="../_modules/django/core/exceptions.html#SynchronousOnlyOperation"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.SynchronousOnlyOperation" title="Lien permanent vers cette définition">¶</a></dt>
<dd><div class="versionadded">
<span class="title">New in Django 3.0.</span> </div>
<p>L’exception <a class="reference internal" href="#django.core.exceptions.SynchronousOnlyOperation" title="django.core.exceptions.SynchronousOnlyOperation"><code class="xref py py-exc docutils literal notranslate"><span class="pre">SynchronousOnlyOperation</span></code></a> est générée lorsque du code qui n’est autorisé que dans un contexte de code Python synchrone est appelé à partir d’un contexte asynchrone (un fil d’exécution avec une boucle événementielle asynchrone en cours). Ces parties de Django sont généralement fortement dépendantes de l’isolation des fils d’exécution pour fonctionner et ne fonctionnent pas correctement avec des coroutines qui partagent un même fil d’exécution.</p>
<p>Si vous essayez d’appeler du code qui est purement synchrone à partir d’un fil d’exécution asynchrone, créez un fil d’exécution synchrone et appelez ce code depuis là. Ceci peut se faire à l’aide de <a class="reference internal" href="../topics/async.html#asgiref.sync.sync_to_async" title="asgiref.sync.sync_to_async"><code class="xref py py-func docutils literal notranslate"><span class="pre">asgiref.sync.sync_to_async()</span></code></a>.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-url-resolver-exceptions">
<span id="url-resolver-exceptions"></span><h2>Exceptions du résolveur d’URL<a class="headerlink" href="#url-resolver-exceptions" title="Lien permanent vers ce titre">¶</a></h2>
<p>Les exceptions du résolveur d’URL sont définies dans <code class="docutils literal notranslate"><span class="pre">django.urls</span></code>.</p>
<div class="section" id="s-resolver404">
<span id="resolver404"></span><h3><code class="docutils literal notranslate"><span class="pre">Resolver404</span></code><a class="headerlink" href="#resolver404" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.urls.Resolver404">
<em class="property">exception </em><code class="descname">Resolver404</code><a class="headerlink" href="#django.urls.Resolver404" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.urls.Resolver404" title="django.urls.Resolver404"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Resolver404</span></code></a> est générée par <a class="reference internal" href="urlresolvers.html#django.urls.resolve" title="django.urls.resolve"><code class="xref py py-func docutils literal notranslate"><span class="pre">django.urls.resolve()</span></code></a> si le chemin transmis à <code class="docutils literal notranslate"><span class="pre">resolve()</span></code> ne correspond à aucune vue. C’est une sous-classe de <a class="reference internal" href="../topics/http/views.html#django.http.Http404" title="django.http.Http404"><code class="xref py py-class docutils literal notranslate"><span class="pre">django.http.Http404</span></code></a>.</p>
</dd></dl>

</div>
<div class="section" id="s-noreversematch">
<span id="noreversematch"></span><h3><code class="docutils literal notranslate"><span class="pre">NoReverseMatch</span></code><a class="headerlink" href="#noreversematch" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.urls.NoReverseMatch">
<em class="property">exception </em><code class="descname">NoReverseMatch</code><a class="headerlink" href="#django.urls.NoReverseMatch" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.urls.NoReverseMatch" title="django.urls.NoReverseMatch"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NoReverseMatch</span></code></a> est générée par <a class="reference internal" href="urlresolvers.html#module-django.urls" title="django.urls"><code class="xref py py-mod docutils literal notranslate"><span class="pre">django.urls</span></code></a> lorsqu’aucune URL contenue dans votre configuration d’URL ne correspond aux paramètres fournis.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-database-exceptions">
<span id="database-exceptions"></span><h2>Exceptions de base de données<a class="headerlink" href="#database-exceptions" title="Lien permanent vers ce titre">¶</a></h2>
<p>Les exceptions de base de données peuvent être importées à partir de <code class="docutils literal notranslate"><span class="pre">django.db</span></code>.</p>
<p>Django adapte les exceptions de base de données standard afin que votre code Django puisse compter sur une implémentation commune de ces classes.</p>
<dl class="exception">
<dt id="django.db.Error">
<em class="property">exception </em><code class="descname">Error</code><a class="headerlink" href="#django.db.Error" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.InterfaceError">
<em class="property">exception </em><code class="descname">InterfaceError</code><a class="headerlink" href="#django.db.InterfaceError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.DatabaseError">
<em class="property">exception </em><code class="descname">DatabaseError</code><a class="headerlink" href="#django.db.DatabaseError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.DataError">
<em class="property">exception </em><code class="descname">DataError</code><a class="headerlink" href="#django.db.DataError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.OperationalError">
<em class="property">exception </em><code class="descname">OperationalError</code><a class="headerlink" href="#django.db.OperationalError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.IntegrityError">
<em class="property">exception </em><code class="descname">IntegrityError</code><a class="headerlink" href="#django.db.IntegrityError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.InternalError">
<em class="property">exception </em><code class="descname">InternalError</code><a class="headerlink" href="#django.db.InternalError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.ProgrammingError">
<em class="property">exception </em><code class="descname">ProgrammingError</code><a class="headerlink" href="#django.db.ProgrammingError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.NotSupportedError">
<em class="property">exception </em><code class="descname">NotSupportedError</code><a class="headerlink" href="#django.db.NotSupportedError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<p>Les adaptateurs Django de ces exceptions de base de données se comportent exactement de la même manière que leurs exceptions sous-jacentes. Consultez la <span class="target" id="index-4"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0249"><strong>PEP 249</strong></a>, la version 2.0 de la spécification Python d’API de base de données,  pour de plus amples informations.</p>
<p>Se conformant à <span class="target" id="index-5"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3134"><strong>PEP 3134</strong></a>, un attribut <code class="docutils literal notranslate"><span class="pre">__cause__</span></code> est défini avec l’exception de base de données sous-jacente, permettant ainsi d’avoir accès à d’éventuelles informations complémentaires.</p>
<dl class="exception">
<dt id="django.db.models.ProtectedError">
<em class="property">exception </em><code class="descclassname">models.</code><code class="descname">ProtectedError</code><a class="headerlink" href="#django.db.models.ProtectedError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<p>Cette exception est générée pour empêcher la suppression d’objets référencés lors de l’utilisation de <a class="reference internal" href="models/fields.html#django.db.models.PROTECT" title="django.db.models.PROTECT"><code class="xref py py-attr docutils literal notranslate"><span class="pre">django.db.models.PROTECT</span></code></a>. <a class="reference internal" href="#django.db.models.ProtectedError" title="django.db.models.ProtectedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">models.ProtectedError</span></code></a> est une sous-classe de <a class="reference internal" href="#django.db.IntegrityError" title="django.db.IntegrityError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IntegrityError</span></code></a>.</p>
<dl class="exception">
<dt id="django.db.models.RestrictedError">
<em class="property">exception </em><code class="descclassname">models.</code><code class="descname">RestrictedError</code><a class="headerlink" href="#django.db.models.RestrictedError" title="Lien permanent vers cette définition">¶</a></dt>
<dd></dd></dl>

<p>Cette exception est générée pour empêcher la suppression d’objets référencés lors de l’utilisation de <a class="reference internal" href="models/fields.html#django.db.models.RESTRICT" title="django.db.models.RESTRICT"><code class="xref py py-attr docutils literal notranslate"><span class="pre">django.db.models.RESTRICT</span></code></a>. <a class="reference internal" href="#django.db.models.RestrictedError" title="django.db.models.RestrictedError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">models.RestrictedError</span></code></a> est une sous-classe de <a class="reference internal" href="#django.db.IntegrityError" title="django.db.IntegrityError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IntegrityError</span></code></a>.</p>
</div>
<div class="section" id="s-http-exceptions">
<span id="http-exceptions"></span><h2>Exceptions Http<a class="headerlink" href="#http-exceptions" title="Lien permanent vers ce titre">¶</a></h2>
<p>Les exceptions HTTP peuvent être importées à partir de <code class="docutils literal notranslate"><span class="pre">django.http</span></code>.</p>
<div class="section" id="s-unreadableposterror">
<span id="unreadableposterror"></span><h3><code class="docutils literal notranslate"><span class="pre">UnreadablePostError</span></code><a class="headerlink" href="#unreadableposterror" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.http.UnreadablePostError">
<em class="property">exception </em><code class="descname">UnreadablePostError</code><a class="headerlink" href="#django.http.UnreadablePostError" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.http.UnreadablePostError" title="django.http.UnreadablePostError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">UnreadablePostError</span></code></a> est générée lorsqu’un utilisateur annule un envoi de fichier.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-transaction-exceptions">
<span id="transaction-exceptions"></span><h2>Exceptions de transaction<a class="headerlink" href="#transaction-exceptions" title="Lien permanent vers ce titre">¶</a></h2>
<p>Les exceptions de transactions sont définies dans <code class="docutils literal notranslate"><span class="pre">django.db.transaction</span></code>.</p>
<div class="section" id="s-transactionmanagementerror">
<span id="transactionmanagementerror"></span><h3><code class="docutils literal notranslate"><span class="pre">TransactionManagementError</span></code><a class="headerlink" href="#transactionmanagementerror" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.db.transaction.TransactionManagementError">
<em class="property">exception </em><code class="descname">TransactionManagementError</code><a class="headerlink" href="#django.db.transaction.TransactionManagementError" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.db.transaction.TransactionManagementError" title="django.db.transaction.TransactionManagementError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TransactionManagementError</span></code></a> est générée lors de tout problème survenant en lien avec les transactions de bases de données.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-testing-framework-exceptions">
<span id="testing-framework-exceptions"></span><h2>Exceptions de l’infrastructure de test<a class="headerlink" href="#testing-framework-exceptions" title="Lien permanent vers ce titre">¶</a></h2>
<p>Exceptions définies dans le paquet <code class="docutils literal notranslate"><span class="pre">django.test</span></code>.</p>
<div class="section" id="s-redirectcycleerror">
<span id="redirectcycleerror"></span><h3><code class="docutils literal notranslate"><span class="pre">RedirectCycleError</span></code><a class="headerlink" href="#redirectcycleerror" title="Lien permanent vers ce titre">¶</a></h3>
<dl class="exception">
<dt id="django.test.client.RedirectCycleError">
<em class="property">exception </em><code class="descclassname">client.</code><code class="descname">RedirectCycleError</code><a class="headerlink" href="#django.test.client.RedirectCycleError" title="Lien permanent vers cette définition">¶</a></dt>
<dd><p>L’exception <a class="reference internal" href="#django.test.client.RedirectCycleError" title="django.test.client.RedirectCycleError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">RedirectCycleError</span></code></a> est générée lorsque le client de test détecte une boucle ou une chaîne de redirection trop longue.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-python-exceptions">
<span id="python-exceptions"></span><h2>Exceptions Python<a class="headerlink" href="#python-exceptions" title="Lien permanent vers ce titre">¶</a></h2>
<p>Django génère également des exceptions intégrées de Python le cas échéant. Consultez la documentation de Python pour plus d’informations concernant les <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#bltin-exceptions" title="(disponible dans Python v3.9)"><span>Built-in Exceptions</span></a>.</p>
</div>
</div>


          </div>
        </div>
      </div>
      
        
          <div class="yui-b" id="sidebar">
            
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="../contents.html">Table of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">Exceptions de Django</a><ul>
<li><a class="reference internal" href="#module-django.core.exceptions">Exceptions principales de Django</a><ul>
<li><a class="reference internal" href="#appregistrynotready"><code class="docutils literal notranslate"><span class="pre">AppRegistryNotReady</span></code></a></li>
<li><a class="reference internal" href="#objectdoesnotexist"><code class="docutils literal notranslate"><span class="pre">ObjectDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#emptyresultset"><code class="docutils literal notranslate"><span class="pre">EmptyResultSet</span></code></a></li>
<li><a class="reference internal" href="#fielddoesnotexist"><code class="docutils literal notranslate"><span class="pre">FieldDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#multipleobjectsreturned"><code class="docutils literal notranslate"><span class="pre">MultipleObjectsReturned</span></code></a></li>
<li><a class="reference internal" href="#suspiciousoperation"><code class="docutils literal notranslate"><span class="pre">SuspiciousOperation</span></code></a></li>
<li><a class="reference internal" href="#permissiondenied"><code class="docutils literal notranslate"><span class="pre">PermissionDenied</span></code></a></li>
<li><a class="reference internal" href="#viewdoesnotexist"><code class="docutils literal notranslate"><span class="pre">ViewDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#middlewarenotused"><code class="docutils literal notranslate"><span class="pre">MiddlewareNotUsed</span></code></a></li>
<li><a class="reference internal" href="#improperlyconfigured"><code class="docutils literal notranslate"><span class="pre">ImproperlyConfigured</span></code></a></li>
<li><a class="reference internal" href="#fielderror"><code class="docutils literal notranslate"><span class="pre">FieldError</span></code></a></li>
<li><a class="reference internal" href="#validationerror"><code class="docutils literal notranslate"><span class="pre">ValidationError</span></code></a><ul>
<li><a class="reference internal" href="#non-field-errors"><code class="docutils literal notranslate"><span class="pre">NON_FIELD_ERRORS</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#requestaborted"><code class="docutils literal notranslate"><span class="pre">RequestAborted</span></code></a></li>
<li><a class="reference internal" href="#synchronousonlyoperation"><code class="docutils literal notranslate"><span class="pre">SynchronousOnlyOperation</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#url-resolver-exceptions">Exceptions du résolveur d’URL</a><ul>
<li><a class="reference internal" href="#resolver404"><code class="docutils literal notranslate"><span class="pre">Resolver404</span></code></a></li>
<li><a class="reference internal" href="#noreversematch"><code class="docutils literal notranslate"><span class="pre">NoReverseMatch</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#database-exceptions">Exceptions de base de données</a></li>
<li><a class="reference internal" href="#http-exceptions">Exceptions Http</a><ul>
<li><a class="reference internal" href="#unreadableposterror"><code class="docutils literal notranslate"><span class="pre">UnreadablePostError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#transaction-exceptions">Exceptions de transaction</a><ul>
<li><a class="reference internal" href="#transactionmanagementerror"><code class="docutils literal notranslate"><span class="pre">TransactionManagementError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#testing-framework-exceptions">Exceptions de l’infrastructure de test</a><ul>
<li><a class="reference internal" href="#redirectcycleerror"><code class="docutils literal notranslate"><span class="pre">RedirectCycleError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#python-exceptions">Exceptions Python</a></li>
</ul>
</li>
</ul>

  <h4>Sujet précédent</h4>
  <p class="topless"><a href="django-admin.html"
                        title="Chapitre précédent"><code class="docutils literal notranslate"><span class="pre">django-admin</span></code> et <code class="docutils literal notranslate"><span class="pre">manage.py</span></code></a></p>
  <h4>Sujet suivant</h4>
  <p class="topless"><a href="files/index.html"
                        title="Chapitre suivant">Gestion des fichiers</a></p>
  <div role="note" aria-label="source link">
    <h3>Cette page</h3>
    <ul class="this-page-menu">
      <li><a href="../_sources/ref/exceptions.txt"
            rel="nofollow">Montrer le code source</a></li>
    </ul>
   </div>
<div id="searchbox" style="display: none" role="search">
  <h3>Recherche rapide</h3>
    <div class="searchformwrapper">
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    </div>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
              <h3>Last update:</h3>
              <p class="topless">oct. 29, 2020</p>
          </div>
        
      
    </div>

    <div id="ft">
      <div class="nav">
    &laquo; <a href="django-admin.html" title="&lt;code class=&#34;docutils literal notranslate&#34;&gt;&lt;span class=&#34;pre&#34;&gt;django-admin&lt;/span&gt;&lt;/code&gt; et &lt;code class=&#34;docutils literal notranslate&#34;&gt;&lt;span class=&#34;pre&#34;&gt;manage.py&lt;/span&gt;&lt;/code&gt;">previous</a>
     |
    <a href="index.html" title="Référence de l’API" accesskey="U">up</a>
   |
    <a href="files/index.html" title="Gestion des fichiers">next</a> &raquo;</div>
    </div>
  </div>

      <div class="clearer"></div>
    </div>
  </body>
</html>